[agent]
  interval = "5s"

[[inputs.cpu]]
  percpu = true
  totalcpu = true

# [[inputs.nvidia_smi]]
#   fieldpass = [
#     "memory_free",
#     "memory_used",
#     "memory_total",
#     "power_draw",
#     "utilization_gpu",
#     "utilization_memory",
#     "temperature_gpu"
#   ]

[[inputs.disk]]
  fieldpass = [
    "free",
    "used",
    "total",
    "used_percent"
  ]

[[inputs.mem]]

[[outputs.opentelemetry]]
  service_address = "otel-collector:4317" 

[[inputs.exec]]
  commands = ["sh /scripts/npu-util.sh 2>/dev/null"]
  timeout = "10s"
  data_format = "json"
  name_override = "npu_usage"
  tag_keys = ["accel_id"]
  json_string_fields = ["accel_id"]
