[agent]
  interval = "10s"

[[inputs.cpu]]
  percpu = true
  totalcpu = true

[[inputs.nvidia_smi]]
  memory_free = true
  memory_used = true
  memory_total = true
  power_draw = true
  utilization_gpu = true
  utilization_memory = true
  power_draw = true

[[inputs.disk]]
  free = true
  used = true
  total = true
  used_percent = true

[[inputs.mem]]

[[outputs.opentelemetry]]
  service_address = "otel-collector:4317" 
