name: Build a Docker image

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the Docker image (optional)'
        required: false
        default: 'latest'
      push-image:
        description: 'Whether to push the image to the registry (true/false)'
        required: false
        type: boolean
        default: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG: ${{ github.event.inputs.tag || 'latest' }}
  PUSH_IMAGE: ${{ github.event.inputs.push-image || 'false' }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./sysfs/Dockerfile
            image: ghcr.io/ksavav/system-metrics-service-sysfs
            context: ./sysfs
          - dockerfile: Dockerfile
            image: ghcr.io/ksavav/system-metrics-service
            context: .
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ matrix.image }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: ${{ env.PUSH_IMAGE == 'true' }}
          tags: ${{ matrix.image }}:${{ env.TAG }}
          labels: ${{ steps.meta.outputs.labels }}
